CREATE TABLE funcionarios(
id INT PRIMARY KEY AUTO_INCREMENT,
nome VARCHAR(100) NOT NULL,
nivel VARCHAR(100) NOT NULL,
senha INT NOT NULL 
);

CREATE TABLE armadura(
id INT PRIMARY KEY AUTO_INCREMENT,
nome VARCHAR(100) NOT NULL,
situacao VARCHAR(100) NOT NULL,
anoFabricacao VARCHAR(100) NOT NULL
);

CREATE TABLE equipamento(
id INT PRIMARY KEY AUTO_INCREMENT,
arma VARCHAR(100) NOT NULL,
municao VARCHAR(100) NOT NULL
);

CREATE TABLE veiculos(
id INT PRIMARY KEY AUTO_INCREMENT, 
veiculo VARCHAR(100) NOT NULL,
placa VARCHAR(100) NOT NULL,
cor VARCHAR(100) NOT NULL
);

CREATE TABLE dispositivoSeguranca(
id INT PRIMARY KEY AUTO_INCREMENT,
nomeDispositivo VARCHAR(100) NOT NULL,
situacao VARCHAR(100) NOT NULL,
disponibilidade VARCHAR(100) NOT NULL
);

CREATE TABLE tarefa(
id INT PRIMARY KEY NOT NULL,
tarefa VARCHAR(100) NOT NULL,
prioridade INT NOT NULL,
funcionario VARCHAR(100) NOT NULL,
situacao VARCHAR(100) NOT NULL
);